version: "3.7"
services:
  app:
    build:
      args:
        user: maks
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: kitchen
    container_name: kitchen-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - kitchen

  db:
    image: mariadb:10.3
    volumes:
      - container-volume:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    container_name: kitchen-db
    restart: always
    environment:
      MYSQL_DATABASE: kitchen
      MYSQL_ROOT_PASSWORD: shehtman.mi
      MYSQL_PASSWORD: password
      MYSQL_USER: kitchen_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - kitchen

  nginx:
    image: nginx:alpine
    container_name: kitchen-nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - kitchen

networks:
  kitchen:
    driver: bridge
volumes:
  container-volume:
